name: Cloud check in action
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: 35 2 * * *
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: user
    steps:
      - name: 🔌 Check out code
        uses: actions/checkout@v4

      - name: 🔨 Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: 👾 Check if Debug is true
        if: vars.debug == '1'
        run: |
          echo "CLOUD189_VERBOSE=1" >> $GITHUB_ENV

      - name: 📹 Restore cached Cookie
        id: cache-cookie-restore
        uses: actions/cache/restore@v4
        with:
          path: .token
          key: cloud189-token-${{ hashFiles('.token/*.json') }}
          restore-keys: cloud189-token-

      - name: 📡 Init dependencies
        run: npm install

      - name: 🚀 Run
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 30
          max_attempts: 3
          command: npm start
        env:
          TY_ACCOUNTS: ${{ secrets.TY_ACCOUNTS }}
          TY_USERNAME_1: ${{ secrets.TY_USERNAME_1 }}
          TY_PASSWORD_1: ${{ secrets.TY_PASSWORD_1 }}
          TY_USERNAME_2: ${{ secrets.TY_USERNAME_2 }}
          TY_PASSWORD_2: ${{ secrets.TY_PASSWORD_2 }}
          TY_USERNAME_3: ${{ secrets.TY_USERNAME_3 }}
          TY_PASSWORD_3: ${{ secrets.TY_PASSWORD_3 }}
          SENDKEY: ${{ secrets.SENDKEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          WECOM_BOT_KEY: ${{ secrets.WECOM_BOT_KEY }}
          WECOM_BOT_TELPHONE: ${{ secrets.WECOM_BOT_TELPHONE }}
          WX_PUSHER_APP_TOKEN: ${{ secrets.WX_PUSHER_APP_TOKEN }}
          WX_PUSHER_UID: ${{ secrets.WX_PUSHER_UID }}
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
          SHOWDOC_KEY: ${{ secrets.SHOWDOC_KEY }}
          BARK_KEY: ${{ secrets.BARK_KEY }}
          BARK_SERVER: ${{ secrets.BARK_SERVER }}

      - name: 🔑 Compute token hash
        if: always()
        run: |
          NEW_HASH=$(find .token -name '*.json' -exec sha256sum {} \; 2>/dev/null | sha256sum | cut -d' ' -f1)
          echo "TOKEN_HASH=${NEW_HASH}" >> $GITHUB_ENV

      - name: 📹 Save cached Cookie
        if: always() && env.TOKEN_HASH != ''
        uses: actions/cache/save@v4
        with:
          path: .token
          key: cloud189-token-${{ env.TOKEN_HASH }}
